compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  '@formspree/react@^2.4.1':
    peerDependencies:
      react: ^18.0.0
      react-dom: ^18.0.0
  babel-loader@^9.1.2:
    dependencies:
      webpack: '>=5'
