nodeLinker: node-modules

packageExtensions:
  "@formspree/react@^2.4.1":
    peerDependencies:
      react: ^18.0.0
      react-dom: ^18.0.0
  stailwc@^0.15.0:
    dependencies:
      "@emotion/serialize": ^1.1.1
  styled-components@^5.3.6:
    dependencies:
      'react-is': '>= 16.8.0'
  'babel-loader@^9.1.2':
    dependencies:
      webpack: '>=5'
  '@storybook/api@^5.1.9':
    dependencies:
      react-dom: '16.x'
  '@storybook/client-api@^5.1.9':
    dependencies:
      react: '^16.0.0'
      react-dom: '16.x'
