version: '3'
services:
  app: &app
    build: .
    ports:
      - '3001:3001'
    command: yarn dev -p 3001
    # Hot Reloadする
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
  # storybook:
  #   <<: *app
  #   ports:
  #     - '6006:6006'
  #   command: yarn storybook -p 6006
