import Head from "next/head"
import React from "react"

export const DefaultHeader = () => (

  <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />

  </Head>
)
