import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import TumblrData from './api/tumblr';
const Home: NextPage = () => {


  if (!TumblrData()) return <div>Loading...</div>

  return (
    <div>
      <Head>

        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/personal_work">personal_work</Link>
      <Link href="/commissioned_work">commissioned_work</Link>
      <Link href="/info">info</Link>
      {TumblrData()?.response.posts.map((post) => {
        return (
          <div key={post.id}>
            <h1>{post.id}</h1>
            <p>{post.caption}</p>
          </div>
        )
      }
      )}

    </div>
  )
}

export default Home
