#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

yarn upgrade:linter
yarn upgrade:types
yarn upgrade:storybook
# yarn lint
yarn unused
npx playwright install
# yarn test
yarn build
