import type { works } from 'libs/@type/work'

export const links: { [key: string]: string | undefined }[] = [
  {
    text: 'Twitter',
    url: process.env.NEXT_PUBLIC_twitter_url,
  },
  {
    text: 'pixiv',
    url: process.env.NEXT_PUBLIC_pixiv_url,
  },
  {
    text: 'Instagram',
    url: process.env.NEXT_PUBLIC_instagram_url,
  },
  {
    text: 'Deviantart',
    url: process.env.NEXT_PUBLIC_deviantart_url,
  },
  {
    text: 'Behance',
    url: process.env.NEXT_PUBLIC_behance_url,
  },
  {
    text: 'Tumblr',
    url: `https://www.tumblr.com/blog/${process.env.NEXT_PUBLIC_Tumblr_username}/`,
    class: 'tumblr',
  },
  {
    text: 'booth',
    url: process.env.NEXT_PUBLIC_booth_url,
  },
]

export const genres = ['文芸書 装画', '文芸誌 扉絵', 'その他']

export const workExperienceEtc: works = [
  {
    genre: 'その他',
    format: 'CDアートワーク',
    title: 'WaVe',
    author: 'ijuice',
    releaseMonth: '2021',
  },
  {
    genre: 'その他',
    format: 'CDアートワーク',
    publisher: 'Virgin Babylon Records',
    title: 'Transform Ordinary Events Into Miracles',
    author: 'Laxenanchaos',
    releaseMonth: '2018-06',
  },
  {
    genre: 'その他',
    author: '月刊MdN 2015年 6月号',
    format: '作品・メイキング掲載',
    publisher: 'エムディエヌコーポレーション',
    title: '創る。',
    releaseMonth: '2015-05',
  },
  {
    genre: 'その他',
    format: 'webアプリ イラスト',
    publisher: '株式会社コムドアーズ',
    title: '六壬式占タロット',
    releaseMonth: '2021-05',
  },
  {
    genre: 'その他',
    format: 'webアプリ イラスト',
    publisher: '株式会社コムドアーズ',
    title: 'ディアスティマタロット',
    releaseMonth: '2019',
  },
  {
    genre: 'その他',
    format: 'webアプリ イラスト',
    publisher: '株式会社コムドアーズ',
    title: '密教曼荼羅タロット',
    releaseMonth: '2017',
  },
  {
    genre: 'その他',
    format: '作品掲載',
    publisher: '翔泳社',
    title: 'ILLUSTRATION 2017',
    releaseMonth: '2016-12',
  },
  {
    genre: 'その他',
    format: '作品掲載',
    publisher: '翔泳社',
    title: 'ILLUSTRATION 2014',
    releaseMonth: '2014-05',
  },
]

export const workExperienceBook: works = [
  {
    genre: '文芸書 装画',
    format: '文庫本',
    publisher: '二見書房',
    title: 'ボギー 怪異考察士の憶測',
    author: '黒史郎',
    designer: 'デザイン 坂野公一 (welle design)',
    releaseMonth: '2021-08',
  },
  {
    genre: '文芸誌 扉絵',
    format: '小説 野性時代',
    publisher: '株式会社KADOKAWA',
    title: '悪の芽',
    author: '貫井徳郎',
    releaseMonth: '2020',
  },
  {
    genre: '文芸書 装画',
    format: '文庫本',
    publisher: '株式会社KADOKAWA',
    title: '少女は夜を綴らない',
    author: '逸木裕',
    designer: 'カバーデザイン 大原由依',
    releaseMonth: '2020-06',
  },
  {
    genre: '文芸書 装画',
    format: '単行本',
    publisher: '早川書房',
    title: 'ファミリーランド',
    author: '澤村伊智',
    designer: '装幀 受川ミドリ',
    releaseMonth: '2019-07',
  },
  {
    genre: '文芸書 装画',
    format: '文庫本',
    publisher: '集英社',
    title: 'スノーマン',
    author: '一雫ライオン',
    releaseMonth: '2018-09',
  },
  {
    genre: '文芸誌 扉絵',
    format: '小説 野性時代',
    publisher: '角川書店',
    title: 'スケルトン・キー',
    author: '道尾秀介',
    releaseMonth: '2018',
  },
  {
    genre: '文芸書 装画',
    format: '文庫本',
    publisher: 'ハーパーコリンズ・ ジャパン',
    title: '15回目の昨日',
    author: 'クリスティン・テリル, 田辺千幸 翻訳',
    designer: 'ブックデザイン albireo',
    releaseMonth: '2018-02',
  },
  {
    genre: '文芸書 装画',
    format: '文庫本',
    publisher: '早川書房',
    title: 'ユートロニカのこちら側',
    author: '小川哲',
    designer: 'カバーデザイン アフターグロウ',
    releaseMonth: '2017-12',
  },
  {
    genre: '文芸誌 扉絵',
    format: 'S-Fマガジン',
    publisher: '早川書房',
    title: 'マリッジ・サバイバー',
    author: '澤村伊智',
    releaseMonth: '2017',
  },
  {
    genre: '文芸誌 扉絵',
    format: 'S-Fマガジン',
    publisher: '早川書房',
    title: '翼の折れた金魚',
    author: '澤村伊智',
    releaseMonth: '2017',
  },
  {
    genre: '文芸書 装画',
    format: '単行本',
    publisher: '早川書房',
    title: 'ゲームの王国 下',
    author: '小川哲',
    designer: 'カバーデザイン 有馬トモユキ',
    releaseMonth: '2017-08',
  },
  {
    genre: '文芸誌 扉絵',
    format: 'S-Fマガジン',
    publisher: '早川書房',
    title: 'コンピューターお義母さん',
    author: '澤村伊智',
    releaseMonth: '2017',
  },
  {
    genre: '文芸書 装画',
    format: '単行本',
    publisher: '角川書店',
    title: 'あとは野となれ大和撫子',
    author: '宮内悠介',
    designer: '装幀 鈴木成一デザイン室',
    releaseMonth: '2017-04',
  },
  {
    genre: '文芸誌 扉絵',
    format: '文芸カドカワ',
    publisher: '角川書店',
    title: '東京の子',
    author: '藤井太洋',
    releaseMonth: '2017',
  },
  {
    genre: '文芸書 装画',
    format: '単行本',
    publisher: '朝日新聞出版',
    title: 'Y.M.G.A.―暴動有資格者',
    author: '三羽省吾',
    designer: '装幀 鈴木成一デザイン室',
    releaseMonth: '2016-02',
  },
  {
    genre: '文芸書 装画',
    format: '単行本',
    publisher: 'ハート出版',
    title: '妻に棲む別人I・II',
    author: '花田深',
    releaseMonth: '2015-12',
  },
  {
    genre: '文芸誌 扉絵',
    format: '文芸カドカワ',
    publisher: '角川書店',
    title: 'あとは野となれ大和撫子',
    author: '宮内悠介',
    releaseMonth: '2015',
  },
  {
    genre: '文芸書 装画',
    format: '単行本',
    publisher: '中央公論新社',
    title: 'マレ・サカチのたったひとつの贈物',
    author: '王城夕紀',
    designer: '装幀 鈴木成一デザイン室',
    releaseMonth: '2015-02',
  },
  {
    genre: '文芸誌 扉絵',
    format: '小説 野性時代',
    publisher: '角川書店',
    title: 's.o.w',
    author: '海猫沢めろん',
    releaseMonth: '2015',
  },
  {
    genre: '文芸書 装画',
    format: '単行本',
    publisher: '講談社',
    title: 'ナイト&シャドウ',
    author: '柳広司',
    designer: 'ブックデザイン 鈴木成一デザイン室',
    releaseMonth: '2014-07',
  },
  {
    genre: '文芸書 装画',
    format: '単行本',
    publisher: '角川書店',
    title: '闇にあかく点るのは、鬼の灯か君の瞳。',
    author: 'ごとうしのぶ',
    designer: '装幀 鈴木成一デザイン室',
    releaseMonth: '2014-02',
  },
  {
    genre: '文芸誌 扉絵',
    format: '小説 野性時代',
    publisher: '角川書店',
    title: 'サロメは金曜',
    author: '海猫沢めろん',
    releaseMonth: '2014',
  },
  {
    genre: '文芸誌 扉絵',
    format: '小説 野性時代',
    publisher: '角川書店',
    title: '水のかげふみ',
    author: '海猫沢めろん',
    releaseMonth: '2014',
  },
  {
    genre: '文芸書 装画',
    format: '文庫本',
    publisher: '大和書房',
    title: '人狼ゲーム~人事の悪夢~',
    author: '鈴木教久',
    designer: 'ブックデザイン 鈴木成一デザイン室',
    releaseMonth: '2014-04',
  },
  {
    genre: '文芸書 装画',
    format: '文庫本',
    publisher: '幻冬舎',
    title: '薔薇の足枷',
    author: '大石圭',
    designer: 'カバーデザイン 平川彰 (幻冬舎デザイン室)',
    releaseMonth: '2013-12',
  },
  {
    genre: '文芸書 装画',
    format: '文庫本',
    publisher: '講談社',
    title: '美しいこと',
    author: '木原音瀬',
    designer: 'カバーデザイン 坂野公一＋吉田友美 (welle design)',
    releaseMonth: '2013-03',
  },
  {
    genre: '文芸書 装画',
    format: '単行本',
    publisher: 'いのちのことば社',
    title: 'スタート・アゲイン (上・下)',
    author: '石川ヨナ',
    designer: 'ブックデザイン 鈴木成一デザイン室',
    releaseMonth: '2011-12',
  },
]

export const workExperience: works = workExperienceEtc.concat(workExperienceBook)
